<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Sankey-Digrams" data-toc-modified-id="Sankey-Digrams-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Sankey Digrams</a></span></li></ul></div>

# Sankey Digrams 

Resources

Used this
https://medium.com/kenlok/how-to-create-sankey-diagrams-from-dataframes-in-python-e221c1b4d6b0

More configuration options here
https://towardsdatascience.com/sankey-diagram-basics-with-pythons-plotly-7a13d557401

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r"CSV\sankey_digram_test_data.csv") # r"C:\Users\ALIENWARE\OneDrive\Python\CSV\sankey_digram_test_data.csv"
df

,lvl1,lvl2_event,lvl2_num_perc,lvl2_display,lvl3,lvl4,MyEDB,count
0,OpenTran 202010,MyEDB month 0,"10 customers, (10%)","MyEDB month 0 : 10 customers, (10%)",salary credit,happy,MyEDB August,5
1,OpenTran 202010,MyEDB month 0,"5 customers, (5%)","MyEDB month 0 : 5 customers, (5%)",non sc,happy,MyEDB August,2
2,OpenTran 202010,MyEDB month 0,"10 customers, (10%)","MyEDB month 0 : 10 customers, (10%)",salary credit,happy,not MyEDB August,3
3,OpenTran 202010,MyEDB month 0,"10 customers, (10%)","MyEDB month 0 : 10 customers, (10%)",non sc,happy,not MyEDB August,8
4,OpenTran 202010,MyEDB month 1,"10 customers, (10%)","MyEDB month 1 : 10 customers, (10%)",salary credit,happy,MyEDB August,2
5,OpenTran 202010,non sc,"10 customers, (10%)","non sc : 10 customers, (10%)",MyEDB month 0,happy,MyEDB August,4
6,OpenTran 202010,salary credit,"10 customers, (10%)","salary credit : 10 customers, (10%)",MyEDB month 0,happy,MyEDB August,1
7,OpenTran 202010,non sc,"10 customers, (10%)","non sc : 10 customers, (10%)",MyEDB month 1,happy,MyEDB August,3
8,OpenTran 202010,not myedb,"10 customers, (10%)","not myedb : 10 customers, (10%)",NaN,NaN,NaN,4
9,OpenTran 202010,not myedb,"10 customers, (10%)","not myedb : 10 customers, (10%)",NaN,NaN,NaN,6
10,OpenTran 202010,not myedb,"10 customers, (10%)","not myedb : 10 customers, (10%)",NaN,NaN,NaN,3

In [ ]:
def genSankey(df,cat_cols=[],value_cols='',title='Sankey Diagram'):
    # maximum of 6 value cols -> 6 colors
    colorPalette = ['#4B8BBE','#306998','#FFE873','#FFD43B','#646464']
    labelList = []
    colorNumList = []
    for catCol in cat_cols:
        labelListTemp =  list(set(df[catCol].values))
        colorNumList.append(len(labelListTemp))
        labelList = labelList + labelListTemp
        
    # remove duplicates from labelList
    labelList = list(dict.fromkeys(labelList))
    
    # define colors based on number of levels
    colorList = []
    for idx, colorNum in enumerate(colorNumList):
        colorList = colorList + [colorPalette[idx]]*colorNum
        
    # transform df into a source-target pair
    for i in range(len(cat_cols)-1):
        if i==0:
            sourceTargetDf = df[[cat_cols[i],cat_cols[i+1],value_cols]]
            sourceTargetDf.columns = ['source','target','count']
        else:
            tempDf = df[[cat_cols[i],cat_cols[i+1],value_cols]]
            tempDf.columns = ['source','target','count']
            sourceTargetDf = pd.concat([sourceTargetDf,tempDf])
        sourceTargetDf = sourceTargetDf.groupby(['source','target']).agg({'count':'sum'}).reset_index()
        
    # add index for source-target pair
    sourceTargetDf['sourceID'] = sourceTargetDf['source'].apply(lambda x: labelList.index(x))
    sourceTargetDf['targetID'] = sourceTargetDf['target'].apply(lambda x: labelList.index(x))
    
    # creating the sankey diagram
    data = dict(
        type='sankey',
        node = dict(
          pad = 15,
          thickness = 20,
          line = dict(
            color = "black",
            width = 0.5
          ),
          label = labelList,
          color = colorList
        ),
        link = dict(
          source = sourceTargetDf['sourceID'],
          target = sourceTargetDf['targetID'],
          value = sourceTargetDf['count']
        )
      )
    
    layout =  dict(
        title = title,
        font = dict(
          size = 10
        )
    )
       
    fig = dict(data=[data], layout=layout)
    return fig

In [ ]:
import pandas as pd
import plotly
#import plotly.plotly as py
import chart_studio.plotly as py

fig = genSankey(df,cat_cols=['lvl1','lvl2_display','lvl3','lvl4', 'MyEDB'],value_cols='count',title='Word Etymology')
plotly.offline.plot(fig, validate=False)